apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-ci-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app-ci
  template:
    metadata:
      labels:
        app: angular-app-ci
    spec:
      containers:
      - name: angular-app-ci
        image: alokg7cr/angular-app-ci
        ports:
        - containerPort: 82
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-ci-srv
spec:
  selector:
    app: angular-app-ci
  ports:
    - name: angular-app-ci
      protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer